[package]
name = "munchausen"
version = "0.1.0"
edition = "2021"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
